export const TicketType = {
  GENERAL_ENTRY: "GENERAL_ENTRY",
  THREE_D_THEATRE: "THREE_D_THEATRE",
  TARAMANDAL: "TARAMANDAL",
};

export const VisitorCategory = {
  INDIVIDUAL: "INDIVIDUAL",
  GROUP: "GROUP",
  GOVT_SCHOOL_COLLEGE: "GOVT_SCHOOL_COLLEGE",
  PRIVATE_SCHOOL_COLLEGE: "PRIVATE_SCHOOL_COLLEGE",
};

export const TicketStatus = {
    CREATED: "CREATED",
    PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
    PAID: "PAID",
    FULLY_REFUNDED: "FULLY_REFUNDED"
};